add aesni-hash-peterrk from smhasher3
MSVC TODO:
aesnihash-peterrk.hpp(99,63): error C2440: 'type cast': cannot convert from '__m128d' to '__m128i'
aesnihash-peterrk.hpp(99,63): message : No constructor could take the source type, or constructor overload resolution was ambiguous
aesnihash-peterrk.hpp(103,62): error C2440: 'type cast': cannot convert from '__m128' to '__m128i'
aesnihash-peterrk.hpp(103,62): message : No constructor could take the source type, or constructor overload resolution was ambiguous